In [1]:
import pandas as pd

#Criando uma DataFrame simples
dados = { 'Nome': ['Mirla', 'Ana', 'Daniel'],
        'Idade': [25, 30, 35],
        'Salario': [5000, 6000, 8000]}
df = pd.DataFrame(dados)
df

     Nome  Idade  Salario
0   Mirla     25     5000
1     Ana     30     6000
2  Daniel     35     8000

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     3 non-null      object
 1   Idade    3 non-null      int64
 2   Salario  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [3]:
df['Salario'].mean()
# ou df.Salario.mean()

np.float64(6333.333333333333)

In [4]:
import pandas as pd

#Criando uma Series simples
idades = pd.Series([45, 30, 45, 40, 25])
idades

0    45
1    30
2    45
3    40
4    25
dtype: int64

In [5]:
idades.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
idades.sort_values()

4    25
1    30
3    40
0    45
2    45
dtype: int64

In [7]:
idades.sort_values(ascending=False)

0    45
2    45
3    40
1    30
4    25
dtype: int64